project:
  type: website

website:
  title: "Solverism"
  favicon: logo-96x96.png
  site-url: https://solverism.com
  repo-url: https://github.com/Blee1077/solverism-quarto-blog
  open-graph: true
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/Blee1077/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
