project:
  type: website

website:
  title: "Solverism"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Blee1077/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



